version: "3.8"
services:
  mongo:
    image: mongo:latest
    container_name: mymongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
